### PR TITLE
Modernize and use HTTP Kit

### PR DESCRIPTION
**Pull request by yurrriq**

### CODE REVIEW

**Comment by l1x** [comment]
Hey @yurrriq what is kicking? I could merge this in if you would like to...

**Comment by yurrriq** [comment]
I meant to make this PR on my fork (oops), but by all means, feel free to use it. It doesn't really change much. You'd want to take out the [project.clj changes](https://github.com/yurrriq/stathat-clojure/commit/4a12d063bd067bf8b3b6c393f749f4590cbf8c04#diff-1) that are [specific](https://github.com/yurrriq/stathat-clojure/blob/4a12d063bd067bf8b3b6c393f749f4590cbf8c04/project.clj#L3) to [me](https://github.com/yurrriq/stathat-clojure/blob/4a12d063bd067bf8b3b6c393f749f4590cbf8c04/project.clj#L5), but other than that it's solid.

**Comment by l1x** [comment]
I don't mind, the stuff specific to you, I might clean it up later.

**Comment by yurrriq** [comment]
:+1:

**Pull request merged**
